# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0005_auto_20170413_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bpdatalist',
            name='bpInformation',
        ),
        migrations.RemoveField(
            model_name='bpinformation',
            name='user',
        ),
        migrations.DeleteModel(
            name='BPDataList',
        ),
        migrations.DeleteModel(
            name='BPInformation',
        ),
        migrations.DeleteModel(
            name='UserInformation',
        ),
    ]
