# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0007_auto_20170413_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRDataInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.PositiveIntegerField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
