# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0010_hrdatainformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrdatainformation',
            name='user',
        ),
        migrations.DeleteModel(
            name='HRDataInformation',
        ),
    ]
