# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0016_dailyactivityinformation_hrdatainformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentHRInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.PositiveIntegerField()),
                ('date_time', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
