# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0017_currenthrinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpdatalist',
            name='measurement_time',
            field=models.DateTimeField(max_length=1000),
        ),
    ]
