# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0019_dailyactivityinformation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpdatalist',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='auth2.UserInformation'),
        ),
        migrations.AlterField(
            model_name='hrdatainformation',
            name='date',
            field=models.DateField(),
        ),
    ]
