# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0020_auto_20170426_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrdatainformation',
            name='date',
        ),
    ]
