# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 06:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0021_remove_hrdatainformation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrdatainformation',
            name='date',
            field=models.DateField(default=datetime.date(1111, 11, 11)),
        ),
    ]
