# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0023_auto_20170426_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenthrinformation',
            name='date_time',
            field=models.DateField(),
        ),
    ]
