# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0024_auto_20170426_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivityinformation',
            name='distance',
            field=models.FloatField(blank=True),
        ),
    ]
