# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0028_delete_dailyactivityinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitBitDailyActivityInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='1111/11/11', max_length=30)),
                ('steps', models.PositiveIntegerField()),
                ('calories', models.PositiveIntegerField()),
                ('distance', models.FloatField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
