# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0029_fitbitdailyactivityinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbitdailyactivityinformation',
            name='calories',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='fitbitdailyactivityinformation',
            name='steps',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
