# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0031_auto_20170428_0354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FitBitDailyActivityInformation',
            new_name='DailyActivityInformation',
        ),
    ]
