# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BPDataList',
        ),
        migrations.DeleteModel(
            name='BPInformation',
        ),
        migrations.DeleteModel(
            name='UserInformation',
        ),
    ]
