# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0008_hrdatainformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HRDataInformation',
        ),
    ]
