# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0011_auto_20170416_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRDataInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.PositiveIntegerField()),
                ('time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth2.UserInformation')),
            ],
        ),
    ]
